### ISSUE TITLE
not latest

### ISSUE THREAD

**Issue by basz** [JSteunou/webstomp-client#33] opened 2017-02-01 15:57 UTC
npm install webstomp-client installs 1.0.3 not 1.0.4

perhaps you should update https://www.npmjs.com/package/webstomp-client ?

**Comment by JSteunou** [comment] 2017-02-01 16:41
Sorry real life got me

closing as dupe of #31 hope I could spend some time on this project this week end.

**Closed as completed by JSteunou** 2017-02-01 16:41 UTC
